ipx::add_bus_interface Noc_0_0_receive [ipx::current_core]
set_property abstraction_type_vlnv xidian:user:Noc_flit_interface_rtl:1.0 [ipx::get_bus_interfaces Noc_0_0_receive -of_objects [ipx::current_core]]
set_property bus_type_vlnv xidian:user:Noc_flit_interface:1.0 [ipx::get_bus_interfaces Noc_0_0_receive -of_objects [ipx::current_core]]
ipx::add_port_map valid [ipx::get_bus_interfaces Noc_0_0_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_0_0_receive_valid [ipx::get_port_maps valid -of_objects [ipx::get_bus_interfaces Noc_0_0_receive -of_objects [ipx::current_core]]]
ipx::add_port_map flit [ipx::get_bus_interfaces Noc_0_0_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_0_0_receive_flit [ipx::get_port_maps flit -of_objects [ipx::get_bus_interfaces Noc_0_0_receive -of_objects [ipx::current_core]]]
ipx::add_port_map vc_ready [ipx::get_bus_interfaces Noc_0_0_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_0_0_receive_vc_ready [ipx::get_port_maps vc_ready -of_objects [ipx::get_bus_interfaces Noc_0_0_receive -of_objects [ipx::current_core]]]
ipx::add_port_map ready [ipx::get_bus_interfaces Noc_0_0_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_0_0_receive_ready [ipx::get_port_maps ready -of_objects [ipx::get_bus_interfaces Noc_0_0_receive -of_objects [ipx::current_core]]]
ipx::add_bus_interface Noc_0_0_sender [ipx::current_core]
set_property abstraction_type_vlnv xidian:user:Noc_flit_interface_rtl:1.0 [ipx::get_bus_interfaces Noc_0_0_sender -of_objects [ipx::current_core]]
set_property bus_type_vlnv xidian:user:Noc_flit_interface:1.0 [ipx::get_bus_interfaces Noc_0_0_sender -of_objects [ipx::current_core]]
set_property interface_mode master [ipx::get_bus_interfaces Noc_0_0_sender -of_objects [ipx::current_core]]
ipx::add_port_map valid [ipx::get_bus_interfaces Noc_0_0_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_0_0_sender_valid [ipx::get_port_maps valid -of_objects [ipx::get_bus_interfaces Noc_0_0_sender -of_objects [ipx::current_core]]]
ipx::add_port_map flit [ipx::get_bus_interfaces Noc_0_0_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_0_0_sender_flit [ipx::get_port_maps flit -of_objects [ipx::get_bus_interfaces Noc_0_0_sender -of_objects [ipx::current_core]]]
ipx::add_port_map vc_ready [ipx::get_bus_interfaces Noc_0_0_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_0_0_sender_vc_ready [ipx::get_port_maps vc_ready -of_objects [ipx::get_bus_interfaces Noc_0_0_sender -of_objects [ipx::current_core]]]
ipx::add_port_map ready [ipx::get_bus_interfaces Noc_0_0_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_0_0_sender_ready [ipx::get_port_maps ready -of_objects [ipx::get_bus_interfaces Noc_0_0_sender -of_objects [ipx::current_core]]]
ipx::add_bus_interface Noc_0_1_receive [ipx::current_core]
set_property abstraction_type_vlnv xidian:user:Noc_flit_interface_rtl:1.0 [ipx::get_bus_interfaces Noc_0_1_receive -of_objects [ipx::current_core]]
set_property bus_type_vlnv xidian:user:Noc_flit_interface:1.0 [ipx::get_bus_interfaces Noc_0_1_receive -of_objects [ipx::current_core]]
ipx::add_port_map valid [ipx::get_bus_interfaces Noc_0_1_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_0_1_receive_valid [ipx::get_port_maps valid -of_objects [ipx::get_bus_interfaces Noc_0_1_receive -of_objects [ipx::current_core]]]
ipx::add_port_map flit [ipx::get_bus_interfaces Noc_0_1_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_0_1_receive_flit [ipx::get_port_maps flit -of_objects [ipx::get_bus_interfaces Noc_0_1_receive -of_objects [ipx::current_core]]]
ipx::add_port_map vc_ready [ipx::get_bus_interfaces Noc_0_1_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_0_1_receive_vc_ready [ipx::get_port_maps vc_ready -of_objects [ipx::get_bus_interfaces Noc_0_1_receive -of_objects [ipx::current_core]]]
ipx::add_port_map ready [ipx::get_bus_interfaces Noc_0_1_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_0_1_receive_ready [ipx::get_port_maps ready -of_objects [ipx::get_bus_interfaces Noc_0_1_receive -of_objects [ipx::current_core]]]
ipx::add_bus_interface Noc_0_1_sender [ipx::current_core]
set_property abstraction_type_vlnv xidian:user:Noc_flit_interface_rtl:1.0 [ipx::get_bus_interfaces Noc_0_1_sender -of_objects [ipx::current_core]]
set_property bus_type_vlnv xidian:user:Noc_flit_interface:1.0 [ipx::get_bus_interfaces Noc_0_1_sender -of_objects [ipx::current_core]]
set_property interface_mode master [ipx::get_bus_interfaces Noc_0_1_sender -of_objects [ipx::current_core]]
ipx::add_port_map valid [ipx::get_bus_interfaces Noc_0_1_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_0_1_sender_valid [ipx::get_port_maps valid -of_objects [ipx::get_bus_interfaces Noc_0_1_sender -of_objects [ipx::current_core]]]
ipx::add_port_map flit [ipx::get_bus_interfaces Noc_0_1_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_0_1_sender_flit [ipx::get_port_maps flit -of_objects [ipx::get_bus_interfaces Noc_0_1_sender -of_objects [ipx::current_core]]]
ipx::add_port_map vc_ready [ipx::get_bus_interfaces Noc_0_1_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_0_1_sender_vc_ready [ipx::get_port_maps vc_ready -of_objects [ipx::get_bus_interfaces Noc_0_1_sender -of_objects [ipx::current_core]]]
ipx::add_port_map ready [ipx::get_bus_interfaces Noc_0_1_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_0_1_sender_ready [ipx::get_port_maps ready -of_objects [ipx::get_bus_interfaces Noc_0_1_sender -of_objects [ipx::current_core]]]
ipx::add_bus_interface Noc_1_0_receive [ipx::current_core]
set_property abstraction_type_vlnv xidian:user:Noc_flit_interface_rtl:1.0 [ipx::get_bus_interfaces Noc_1_0_receive -of_objects [ipx::current_core]]
set_property bus_type_vlnv xidian:user:Noc_flit_interface:1.0 [ipx::get_bus_interfaces Noc_1_0_receive -of_objects [ipx::current_core]]
ipx::add_port_map valid [ipx::get_bus_interfaces Noc_1_0_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_1_0_receive_valid [ipx::get_port_maps valid -of_objects [ipx::get_bus_interfaces Noc_1_0_receive -of_objects [ipx::current_core]]]
ipx::add_port_map flit [ipx::get_bus_interfaces Noc_1_0_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_1_0_receive_flit [ipx::get_port_maps flit -of_objects [ipx::get_bus_interfaces Noc_1_0_receive -of_objects [ipx::current_core]]]
ipx::add_port_map vc_ready [ipx::get_bus_interfaces Noc_1_0_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_1_0_receive_vc_ready [ipx::get_port_maps vc_ready -of_objects [ipx::get_bus_interfaces Noc_1_0_receive -of_objects [ipx::current_core]]]
ipx::add_port_map ready [ipx::get_bus_interfaces Noc_1_0_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_1_0_receive_ready [ipx::get_port_maps ready -of_objects [ipx::get_bus_interfaces Noc_1_0_receive -of_objects [ipx::current_core]]]
ipx::add_bus_interface Noc_1_0_sender [ipx::current_core]
set_property abstraction_type_vlnv xidian:user:Noc_flit_interface_rtl:1.0 [ipx::get_bus_interfaces Noc_1_0_sender -of_objects [ipx::current_core]]
set_property bus_type_vlnv xidian:user:Noc_flit_interface:1.0 [ipx::get_bus_interfaces Noc_1_0_sender -of_objects [ipx::current_core]]
set_property interface_mode master [ipx::get_bus_interfaces Noc_1_0_sender -of_objects [ipx::current_core]]
ipx::add_port_map valid [ipx::get_bus_interfaces Noc_1_0_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_1_0_sender_valid [ipx::get_port_maps valid -of_objects [ipx::get_bus_interfaces Noc_1_0_sender -of_objects [ipx::current_core]]]
ipx::add_port_map flit [ipx::get_bus_interfaces Noc_1_0_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_1_0_sender_flit [ipx::get_port_maps flit -of_objects [ipx::get_bus_interfaces Noc_1_0_sender -of_objects [ipx::current_core]]]
ipx::add_port_map vc_ready [ipx::get_bus_interfaces Noc_1_0_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_1_0_sender_vc_ready [ipx::get_port_maps vc_ready -of_objects [ipx::get_bus_interfaces Noc_1_0_sender -of_objects [ipx::current_core]]]
ipx::add_port_map ready [ipx::get_bus_interfaces Noc_1_0_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_1_0_sender_ready [ipx::get_port_maps ready -of_objects [ipx::get_bus_interfaces Noc_1_0_sender -of_objects [ipx::current_core]]]
ipx::add_bus_interface Noc_1_1_receive [ipx::current_core]
set_property abstraction_type_vlnv xidian:user:Noc_flit_interface_rtl:1.0 [ipx::get_bus_interfaces Noc_1_1_receive -of_objects [ipx::current_core]]
set_property bus_type_vlnv xidian:user:Noc_flit_interface:1.0 [ipx::get_bus_interfaces Noc_1_1_receive -of_objects [ipx::current_core]]
ipx::add_port_map valid [ipx::get_bus_interfaces Noc_1_1_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_1_1_receive_valid [ipx::get_port_maps valid -of_objects [ipx::get_bus_interfaces Noc_1_1_receive -of_objects [ipx::current_core]]]
ipx::add_port_map flit [ipx::get_bus_interfaces Noc_1_1_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_1_1_receive_flit [ipx::get_port_maps flit -of_objects [ipx::get_bus_interfaces Noc_1_1_receive -of_objects [ipx::current_core]]]
ipx::add_port_map vc_ready [ipx::get_bus_interfaces Noc_1_1_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_1_1_receive_vc_ready [ipx::get_port_maps vc_ready -of_objects [ipx::get_bus_interfaces Noc_1_1_receive -of_objects [ipx::current_core]]]
ipx::add_port_map ready [ipx::get_bus_interfaces Noc_1_1_receive -of_objects [ipx::current_core]]
set_property physical_name Noc_1_1_receive_ready [ipx::get_port_maps ready -of_objects [ipx::get_bus_interfaces Noc_1_1_receive -of_objects [ipx::current_core]]]
ipx::add_bus_interface Noc_1_1_sender [ipx::current_core]
set_property abstraction_type_vlnv xidian:user:Noc_flit_interface_rtl:1.0 [ipx::get_bus_interfaces Noc_1_1_sender -of_objects [ipx::current_core]]
set_property bus_type_vlnv xidian:user:Noc_flit_interface:1.0 [ipx::get_bus_interfaces Noc_1_1_sender -of_objects [ipx::current_core]]
set_property interface_mode master [ipx::get_bus_interfaces Noc_1_1_sender -of_objects [ipx::current_core]]
ipx::add_port_map valid [ipx::get_bus_interfaces Noc_1_1_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_1_1_sender_valid [ipx::get_port_maps valid -of_objects [ipx::get_bus_interfaces Noc_1_1_sender -of_objects [ipx::current_core]]]
ipx::add_port_map flit [ipx::get_bus_interfaces Noc_1_1_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_1_1_sender_flit [ipx::get_port_maps flit -of_objects [ipx::get_bus_interfaces Noc_1_1_sender -of_objects [ipx::current_core]]]
ipx::add_port_map vc_ready [ipx::get_bus_interfaces Noc_1_1_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_1_1_sender_vc_ready [ipx::get_port_maps vc_ready -of_objects [ipx::get_bus_interfaces Noc_1_1_sender -of_objects [ipx::current_core]]]
ipx::add_port_map ready [ipx::get_bus_interfaces Noc_1_1_sender -of_objects [ipx::current_core]]
set_property physical_name Noc_1_1_sender_ready [ipx::get_port_maps ready -of_objects [ipx::get_bus_interfaces Noc_1_1_sender -of_objects [ipx::current_core]]]
